### ISSUE TITLE
How to use rl2_eval.py?

### ISSUE THREAD

**Issue by lucifer2859** [chanb/metalearning_RL#5]
How to use rl2_eval.py?

**Comment by lucifer2859** [comment]
parser.add_argument('--eval_tasks', help='the tasks to evaluate on')
metalearning_RL/logs_eval/* ?

**Comment by chanb** [comment]
For `eval_tasks` specifically, you need to run `generate_tasks.py` which generates a pickle file consisting of the configurations of the `num_tasks` environments. You then pass the path of the generated pickle file to `eval_tasks`.

To explain the `rl2_eval.py` slightly more, you have the option to evaluate on trained models using `rl2_train.py` and Uniform sampling. To run the former, you need to set `algo=ppo` and provide `models_dir`. `models_dir` is generated running `rl2_train.py`. To run the latter, you can set `algo` to anything but `ppo`, then pass in `num_fake_update` and `skip`, which are used to match the update interval that you used for training the RL^2 agent.
e.g. if I made a total of 300 updates but I only save every 5 updates for the RL^2 agent, I would set `num_fake_update=300` and `skip=5` so the results can be generated in a consistent manner.

`metalearning_RL/logs_eval/*` contains some of the results that we got when we were actively working on this project.

Thank you for the interest in our repo!
